server:
  port: 8201
spring:
  application:
    name: mall-gateway
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
zuul:
  retryable: true
  add-host-header: true  # 添加header
  sensitive-headers:     # 把敏感头去掉
ribbon:
  ConnectTimeout: 1500 # 连接超时时间(ms)
  ReadTimeout: 5000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
  rabbitmq: #rabbitmq相关配置
      host: localhost
      port: 5672
      username: guest
      password: guest
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8001/eureka/
  management:
    endpoints:
      web:
        exposure:
          include: 'refresh'
logging:
  level:
    org.springframework.cloud.gateway: debug
